### PR TITLE
Fix #8033 - Open node from the object inspector in popups

### LINKED ISSUE #8033: Can't select node from the Popup
**Steps to reproduce**
1. Go to https://nchevobbe.github.io/demo/console-test-app.html
1. Open the debugger
1. Open `console-test-event-listeners.js`, and add a breakpoint on line 6 (inside the click event handler)
1. In the page, click on a button
1. The debugger should pause, now hover `e`
1. There should be a `target` property, with an icon next to it, click the icon

**Expected results**

The target element is selected in the inspector, like the title claim it will.

**Actual results**

Nothing is happening.

### PR DESCRIPTION
**Pull request by darkwing**
Fixes #8033

## Testing

Check out the STR here:  https://github.com/firefox-devtools/debugger/issues/8033

### CODE REVIEW

File: src/components/Editor/Preview/Popup.js [hunk 1]
```diff
@@ -318,15 +318,15 @@ export class Popup extends Component<Props, State> {
...
+  popupObjectProperties: getAllPopupObjectProperties(state)
 });
 
 const {
   addExpression,
   selectSourceURL,
   setPopupObjectProperties,
-  openLink
+  openLink,
+  openElementInInspector: actions.openElementInInspectorCommand
```
Comment (jasonLaster) [inline src/components/Editor/Preview/Popup.js]: this seems more reasonable from the outside 


```diff
diff --git a/src/components/Editor/Preview/Popup.js b/src/components/Editor/Preview/Popup.js
index 71412576f..039ccb955 100644
--- a/src/components/Editor/Preview/Popup.js
+++ b/src/components/Editor/Preview/Popup.js
@@ -325,15 +325,15 @@ const {
   addExpression,
   selectSourceURL,
   setPopupObjectProperties,
-  openLink,
-  openElementInInspector: actions.openElementInInspectorCommand
+  openLink
 } = actions;

 const mapDispatchToProps = {
   addExpression,
   selectSourceURL,
   setPopupObjectProperties,
-  openLink
+  openLink,
+  openElementInInspector: actions.openElementInInspectorCommand
 };

 export default connect(
```

Comment (darkwing) [reply src/components/Editor/Preview/Popup.js]: *sigh* bad copy/paste from MC.  Fixing now.

Comment (jasonLaster) [reply src/components/Editor/Preview/Popup.js]: de nada, feel free to open in phabricator as well

File: test/mochitest/browser_dbg-inspector-integration.js [hunk 2]
```diff
@@ -24,4 +25,23 @@ add_task(async function() {
...
+
+  findElement(dbg, "frame", 2).focus();
+  await clickElement(dbg, "frame", 2);
+
+  // Hover over the token to launch preview popup
+  await tryHovering(dbg, 5, 8, "popup");
+
+  // Click the first inspector buttom to view node in inspector
+  await waitForElementWithSelector(dbg, "button.open-inspector");
+  findElementWithSelector(dbg, "button.open-inspector").click();
```
Comment (jasonLaster) [inline test/mochitest/browser_dbg-inspector-integration.js]: nit: it would be nice to name this selector so that we can re-use it in other tests and if the class name changes change it in one place
